DROP TABLE IF EXISTS PIZZA;
DROP TABLE IF EXISTS ORD_PIZZA;

CREATE TABLE PIZZA (
id IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
price DECIMAL(5,2) NOT NULL,
ingredients VARCHAR(500)
);

CREATE TABLE ORD_PIZZA (
cod IDENTITY PRIMARY KEY,
pizza INT NOT NULL,
stato VARCHAR(20) NOT NULL,
CONSTRAINT fk_pizza FOREIGN KEY (pizza) REFERENCES PIZZA(id) ON DELETE CASCADE
);